services:
  trilium:
    image: triliumnext/notes:latest
    container_name: trilium
    ports:
      - "8090:8080"
    volumes:
      - ${TRILIUM_DATA}:/home/node/trilium-data
    restart: unless-stopped
    networks:
      - trilium_net

networks:
  trilium_net:
    driver: bridge
    ipam:
      config:
        - subnet: ${TRILIUM_SUBNET}
