services:

  nginx-static:
    image: flashspys/nginx-static:latest
    container_name: nginx-static
    volumes:
      - ${LANDING_PAGE_DATA}:/static
    ports:
      - ${LANDING_PAGE_HOST_PORT}:80
    restart: unless-stopped
    networks:
      - landing_page_network

networks:
  landing_page_network:
    driver: bridge
    ipam:
      config:
        - subnet: ${LANDING_PAGE_NETWORK}
